spring:
  application:
    name: bbc

  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
    username: bbc
    password: bbc
  sql:
    init:
      mode: always
      continue-on-error: true
